name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Ensure shell scripts are executable
        run: |
          chmod +x ./.github/scripts/wait-for-postgres.sh
          chmod +x ./.github/scripts/wait-for-keycloak.sh

      - name: Wait for PostgreSQL to be healthy
        env:
          TIMEOUT: 120
          INTERVAL: 5
        run: |
          ./.github/scripts/wait-for-postgres.sh
        shell: bash

      - name: Wait for Keycloak to be ready
        env:
          TIMEOUT: 120
          INTERVAL: 5
        run: |
          ./.github/scripts/wait-for-keycloak.sh
        shell: bash

      - name: Build and run tests
        run: mvn -B test --file pom.xml

      - name: Package application
        run: mvn -B package --file pom.xml -DskipTests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/mydatabase
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
          KEYCLOAK_ISSUER_URI: http://localhost:8090/realms/RssFeedAggregator
          KEYCLOAK_CLIENT-ID: rss-feed-client

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      - name: Shut down Docker Compose services
        run: docker-compose down
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and run tests
        run: mvn -B test --file pom.xml
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning